[theme]
primaryColor = "#F0532D"             # Laranja marcante da marca
backgroundColor = "#0D0F11"          # Preto acinzentado (mais elegante que puro preto)
secondaryBackgroundColor = "#1A1C1F" # Cartões e áreas de conteúdo com contraste suave
textColor = "#ECECEC"                # Cinza quase branco (menos agressivo que #FFF)
